<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xs="http://www.w3.org/2001/XMLSchema"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:cnt="urn:ru:rt:hrms:context"
                  xmlns:scc="urn:ru:rt:hrms:successresponse" xmlns:flt="urn:ru:rt:hrms:fault"
                  xmlns:tns="urn:ru:rt:hrms:errortransferservice" targetNamespace="urn:ru:rt:hrms:errortransferservice">
  <wsdl:types>
    <xs:schema targetNamespace="urn:ru:rt:hrms:errortransferservice" xmlns:xs="http://www.w3.org/2001/XMLSchema">
      <xs:import namespace="urn:ru:rt:hrms:successresponse"
                 schemaLocation="http://10.32.245.8:7001/HermesSOAPService/SOAPServlet/TransferFaultRequest?xsd=1"/>
      <xs:import namespace="urn:ru:rt:hrms:fault"
                 schemaLocation="http://10.32.245.8:7001/HermesSOAPService/SOAPServlet/TransferFaultRequest?xsd=2"/>
      <xs:import namespace="urn:ru:rt:hrms:context"
                 schemaLocation="http://10.32.245.8:7001/HermesSOAPService/SOAPServlet/TransferFaultRequest?xsd=3"/>
    </xs:schema>
  </wsdl:types>
  <wsdl:message name="Fault">
    <wsdl:part name="message" element="flt:Fault"/>
  </wsdl:message>
  <wsdl:message name="Context">
    <wsdl:part name="context" element="cnt:Context"/>
  </wsdl:message>
  <wsdl:message name="SuccessResponse">
    <wsdl:part name="message" element="scc:SuccessResponse"/>
  </wsdl:message>
  <wsdl:portType name="HRMSPortType">
    <wsdl:operation name="TransferFault">
      <wsdl:input name="TransferFaultIn" message="tns:Fault"/>
      <wsdl:output message="tns:SuccessResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="HRMSBinding" type="tns:HRMSPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="TransferFault">
      <wsdl:documentation>Сервис информирования системы-источника запроса об ошибках при взаимодействии ФЕИП и CУС "Гермес"</wsdl:documentation>
      <soap:operation soapAction="urn:ru:rt:ruip:errortransferservice:TransferFault"/>
      <wsdl:input name="TransferFaultIn">
        <soap:header message="tns:Context" part="context" use="literal"/>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="HRMSService">
    <wsdl:port name="HRMSInterface" binding="tns:HRMSBinding">
      <soap:address location="http://10.32.245.8:7001/HermesSOAPService/SOAPServlet/TransferFaultRequest"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>